export const REDUX_BRIDGE_REGISTER_WEB_VIEW = 'REDUX_BRIDGE_REGISTER_WEB_VIEW';
export const REDUX_BRIDGE_UNREGISTER_WEB_VIEW = 'REDUX_BRIDGE_UNREGISTER_WEB_VIEW';
export const REDUX_BRIDGE_SYNC_INITIAL_STATE = 'REDUX_BRIDGE_SYNC_INITIAL_STATE';
export const REDUX_BRIDGE_REQUEST_INITIAL_STATE = 'REDUX_BRIDGE_REQUEST_INITIAL_STATE';
